micronaut:
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M #every minute

endpoints:
  prometheus:
    enabled: true
    sensitive: false